# Generated by Django 5.2.7 on 2025-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_sold',
            new_name='is_new',
        ),
        migrations.AddField(
            model_name='item',
            name='quatity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
