# Generated by Django 5.2.7 on 2025-10-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='User Profile',
        ),
    ]
