# Generated by Django 5.2.7 on 2025-10-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='quatity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
